SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 200  # milliseconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED = 400

PLAYER_RADIUS = 20
PLAYER_SPEED = 300
PLAYER_TURN_SPEED = 300

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOT_COOLDOWN = 0.3
